

services:
  db:                                # 服务名（容器别名）：db
    image: pgvector/pgvector:pg16    # 使用已内置 pgvector 的 Postgres 16 镜像
    environment:                     # 设置数据库环境变量
      POSTGRES_USER: app             # 数据库用户名
      POSTGRES_PASSWORD: app         # 数据库密码
      POSTGRES_DB: shop              # 初始数据库名
    ports:
      - "5432:5432"                  # 把容器的 5432 映射到本机 5432
    volumes:
      - db_data:/var/lib/postgresql/data  # 持久化数据到本机卷，重启不丢数据

  redis:                             # Redis 服务
    image: redis:7
    ports:
      - "6379:6379"                   # 容器 6379 映射到本机 6379
    command: ["redis-server", "--appendonly", "yes"] 
    volumes:
      - redis_data:/data              # 数据持久化（可选）

volumes:
  db_data: {}                        # 定义上面用到的数据卷
  redis_data: {}
